apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: travel-booking-system
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin_keycloak
  KC_BOOTSTRAP_ADMIN_PASSWORD: 9wJ7nWRk4L
