apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: travel-booking-system
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 4455
      protocol: TCP
