apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
{{- $file := "configurations/travel-booking-system-realm.json" }}
  {{ base $file }}: |-
{{- .Files.Get $file | nindent 4 }}
