apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
{{- $file := "configurations/keycloak.conf" }}
  {{ base $file }}: |-
{{- .Files.Get $file | nindent 4 }}
