apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.name" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin_keycloak"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "9wJ7nWRk4L"
