argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
