apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: redis
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
        - name: redis
          image: redis:8.2.1
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
