apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-travel-booking-system
  labels:
    db: redis-travel-booking-system
spec:
  selector:
    matchLabels:
      db: redis-travel-booking-system
  template:
    metadata:
      labels:
        db: redis-travel-booking-system
    spec:
      containers:
        - name: redis-travel-booking-system
          image: redis:8.2.1
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi