apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  namespace: travel-booking-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      name: flight-service
      labels:
        app: flight-service
    spec:
      containers:
        - name: flight-service
          imagePullPolicy: IfNotPresent
          image: ghcr.io/vasimvahabov/flight-service:0.8.0
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          ports:
            - containerPort: 8001
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              port: 8001
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            httpGet:
              port: 8001
              path: /actuator/health/readiness
          volumeMounts:
            - name: flight-service-config
              mountPath: /workspace/config
      volumes:
        - name: flight-service-config
          configMap:
            name: flight-service-config
