apiVersion: v1
kind: Service
metadata:
  name: flight-service
  labels:
    app: flight-service
spec:
  type: ClusterIP
  selector:
    app: flight-service
  ports:
    - port: 8899
      targetPort: 8899
