apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server
  namespace: travel-booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
    spec:
      containers:
        - name: edge-server
          image: ghcr.io/vasimvahabov/edge-server:0.7.0
          imagePullPolicy: IfNotPresent
          ports:
             - containerPort: 8003
          env:
            - name: FLIGHT_SERVICE_URL
              value: http://flight-service
            - name: FLIGHT_BOOKING_SERVICE_URL
              value: http://flight-booking-service
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: OAUTH2_ISSUER_URI
              value: http://keycloak:8080/realms/travel-booking-system
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8003
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            httpGet:
              port: 8003
              path: /actuator/health/readiness

