services:
  payment-service:
    image: ${IMAGE_NAME_PAYMENT_SERVICE}:${IMAGE_VERSION_PAYMENT_SERVICE}
    pull_policy: missing
    container_name: payment-service
    ports:
      - "5566:5566"
      - "5656:5656"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 5656
      SPRING_RABBITMQ_HOST: rabbitmq-travel-booking-system
    networks:
      - network-travel-booking-system
    depends_on:
      - rabbitmq-travel-booking-system

  edge-server:
    image: ${IMAGE_NAME_EDGE_SERVER}:${IMAGE_VERSION_EDGE_SERVER}
    pull_policy: missing
    container_name: edge-server
    ports:
      - "6677:6677"
      - "6767:6767"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 6767
      SPRING_DATA_REDIS_HOST: redis-travel-booking-system
      FLIGHT_SERVICE_URI: http://flight-service:8899
      FLIGHT_BOOKING_SERVICE_URI: http://flight-booking-service:7788
    networks:
      - network-travel-booking-system
    depends_on:
      - redis-travel-booking-system

  flight-booking-service:
    image: ${IMAGE_NAME_FLIGHT_BOOKING_SERVICE}:${IMAGE_VERSION_FLIGHT_BOOKING_SERVICE}
    pull_policy: missing
    container_name: flight-booking-service
    ports:
      - "7788:7788"
      - "7878:7878"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 7878
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-travel-booking-system:5432/flight_bookings
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres-travel-booking-system:5432/flight_bookings
      TRAVEL_BOOKING_SYSTEM_FLIGHT_SERVICE_URI: http://flight-service:8899
      SPRING_RABBITMQ_HOST: rabbitmq-travel-booking-system
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres-travel-booking-system

  flight-service:
    image: ${IMAGE_NAME_FLIGHT_SERVICE}:${IMAGE_VERSION_FLIGHT_SERVICE}
    pull_policy: missing
    container_name: flight-service
    ports:
      - "8899:8899"
      - "8989:8989"
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8989
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-travel-booking-system:5432/flights
#      APPLICATION_TEST_DATA_ENABLED: true
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres-travel-booking-system

  pgadmin-travel-booking-system:
    image: dpage/pgadmin4:${IMAGE_VERSION_PGADMIN}
    pull_policy: missing
    container_name: pgadmin-travel-booking-system
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5000:80"
    networks:
      - network-travel-booking-system

  postgres-travel-booking-system:
    image: postgres:${IMAGE_VERSION_POSTGRES}
    pull_policy: missing
    container_name: postgres-travel-booking-system
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network-travel-booking-system

  redis-travel-booking-system:
    image: redis:${IMAGE_VERSION_REDIS}
    pull_policy: missing
    container_name: redis-travel-booking-system
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - network-travel-booking-system

  rabbitmq-travel-booking-system:
    image: rabbitmq:${IMAGE_VERSION_RABBITMQ}
    container_name: rabbitmq-travel-booking-system
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-data:/var/log/rabbitmq
    networks:
      - network-travel-booking-system

  keycloak-travel-booking-system:
    image: keycloak/keycloak:${IMAGE_VERSION_KEYCLOAK}
    container_name: keycloak-travel-booking-system
#    command: start-dev
    command: start-dev --import-realm
    ports:
      - "4455:4455"
      - "4545:4545"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_PORT: 4455
    volumes:
#      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres-travel-booking-system

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
  rabbitmq-data:
    name: rabbitmq-data

networks:
  network-travel-booking-system:
    name: network-travel-booking-system
    driver: bridge
#    external: true