services:
  payment-service:
    image: ${IMAGE_NAME_PAYMENT_SERVICE}:${IMAGE_VERSION_PAYMENT_SERVICE}
    pull_policy: missing
    container_name: payment-service
    ports:
      - "8004:8004"
      - "7004:7004"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 7004
      SPRING_RABBITMQ_HOST: rabbitmq
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: 127.0.0.1:24224
    networks:
      - network-travel-booking-system
    depends_on:
      - rabbitmq

  edge-server:
    image: ${IMAGE_NAME_EDGE_SERVER}:${IMAGE_VERSION_EDGE_SERVER}
    pull_policy: missing
    container_name: edge-server
    ports:
      - "8003:8003"
      - "7003:7003"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 7003
      SPRING_DATA_REDIS_HOST: redis
      FLIGHT_SERVICE_URI: http://flight-service:8001
      FLIGHT_BOOKING_SERVICE_URI: http://flight-booking-service:8002
      OAUTH2_ISSUER_URI: http://keycloak:8080/realms/travel-booking-system
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: 127.0.0.1:24224
    networks:
      - network-travel-booking-system
    depends_on:
      - redis
      - keycloak

  flight-booking-service:
    image: ${IMAGE_NAME_FLIGHT_BOOKING_SERVICE}:${IMAGE_VERSION_FLIGHT_BOOKING_SERVICE}
    pull_policy: missing
    container_name: flight-booking-service
    ports:
      - "8002:8002"
      - "7002:7002"
    environment:
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 7002
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/flight_bookings
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/flight_bookings
      TRAVEL_BOOKING_SYSTEM_FLIGHT_SERVICE_URI: http://flight-service:8001
      SPRING_RABBITMQ_HOST: rabbitmq
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: 127.0.0.1:24224
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres

  flight-service:
    image: ${IMAGE_NAME_FLIGHT_SERVICE}:${IMAGE_VERSION_FLIGHT_SERVICE}
    pull_policy: missing
    container_name: flight-service
    ports:
      - "8001:8001"
      - "7001:7001"
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 7001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flights
      JWT_ISSUER_URI: http://keycloak:4455/realms/travel-booking-system
    #      APPLICATION_TEST_DATA_ENABLED: true
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: 127.0.0.1:24224
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres
      - fluent-bit

  pgadmin:
    image: dpage/pgadmin4:${IMAGE_VERSION_PGADMIN}
    pull_policy: missing
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5000:80"
    networks:
      - network-travel-booking-system

  postgres:
    image: postgres:${IMAGE_VERSION_POSTGRES}
    pull_policy: missing
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network-travel-booking-system

  redis:
    image: redis:${IMAGE_VERSION_REDIS}
    pull_policy: missing
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - network-travel-booking-system

  rabbitmq:
    image: rabbitmq:${IMAGE_VERSION_RABBITMQ}
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/log/rabbitmq
    networks:
      - network-travel-booking-system

  keycloak:
    image: keycloak/keycloak:${IMAGE_VERSION_KEYCLOAK}
    container_name: keycloak
#    command: start-dev
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak
      KC_HTTP_PORT: 8080
    volumes:
      - ./keycloak/config:/opt/keycloak/conf/
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - network-travel-booking-system
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:${IMAGE_VERSION_PROMETHEUS}
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - network-travel-booking-system

  grafana:
    image: grafana/grafana:${IMAGE_VERSION_GRAFANA}
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./observability/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./observability/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    networks:
      - network-travel-booking-system
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:${IMAGE_VERSION_LOKI}
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - network-travel-booking-system
    depends_on:
      - fluent-bit

  fluent-bit:
    image: fluent/fluent-bit:${IMAGE_VERSION_FLUENT_BIT}
    container_name: fluent-bit
    ports:
      - "24224:24224"
    command: [ "-c", "/fluent-bit/etc/fluent-bit.yaml" ]
    environment:
      LOKI_HOST: ${LOKI_HOST}
    volumes:
      - ./observability/fluent-bit/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    networks:
      - network-travel-booking-system

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
  rabbitmq-data:
    name: rabbitmq-data
  loki-data:
    name: loki-data
  grafana-data:
    name: grafana-data
  prometheus-data:
    name: prometheus-data

networks:
  network-travel-booking-system:
    name: network-travel-booking-system
    driver: bridge
#    external: true
