apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: user_postgres
            - name: POSTGRES_PASSWORD
              value: 6eEvI63t20
#            - name: POSTGRES_DB
#              value: flights
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-init
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
