apiVersion: v1
kind: Service
metadata:
  name: postgres-travel-booking-system
  labels:
    db: postgres-travel-booking-system
spec:
  type: ClusterIP
  selector:
    db: postgres-travel-booking-system
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432