apiVersion: 1

deleteDatasources:
  - name: loki-travel-booking-system

datasources:
  - name: loki-travel-booking-system
    type: loki
    uid: loki-travel-booking-system
    orgId: 1
    typeName: Loki
    typeLogoUrl: public/plugins/loki/img/loki_icon.svg
    access: proxy
    url: 'http://loki-travel-booking-system:3100'
    basicAuth: false
    isDefault: true
    editable: true
