apiVersion: 1

deleteDatasources:
  - name: Loki
  - name: Prometheus

datasources:
  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    typeName: Loki
    typeLogoUrl: public/plugins/loki/img/loki_icon.svg
    access: proxy
    url: 'http://loki:3100'
    basicAuth: false
    isDefault: true
    editable: true
    version: 1
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    typeName: Loki
    typeLogoUrl: public/plugins/prometheus/img/prometheus_icon.svg
    access: proxy
    url: 'http://prometheus:9090'
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
