name: Commit Stage
on: push

jobs:
  validate:
    name: Validate K8S manifests
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          kubectl: '1.24.10'
          kubeconform: '0.5.0'
      - name: test
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        run: |
          kubeconform -strict -verbose k8s/flight-service/manifests
          kubeconform -strict -verbose k8s/postgress/manifests