server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

usage_report:
  reporting_enabled: false
